### ISSUE TITLE
Pydantic update breaks proxies + proxies cannot search for more than 50

### ISSUE THREAD

**Issue by m-ruiz21** [m-ruiz21/SpotifyRecommender#25]
Two issues with the proxies:
- Pydantic update has broken the tekore union types and thus the proxies. 
- - Reference: https://github.com/pydantic/pydantic/issues/8119
- Proxy currently cannot send more than 50 playlists currently because of Spotify search limits. Search in batches needs to be implemented.

**Comment by felix-hilden** [comment]
Hi, just saw this referencing the issue I created, Tekore author here 👋 Thought I'd drop in to say if you just care about raw numbers and to build a feature (mind you I have very little context to what you're trying to do) we already have builtin paging iterators! Check [this guide](https://tekore.readthedocs.io/en/stable/advanced_usage.html#maximise-limits) out.

**Comment by m-ruiz21** [comment]
I already fixed it, but thank you so much! I’ll definitely use this if I need to go around the limits again. I love your library and it’s been so useful to me in this project :) Andrés Mateo Ruiz FloresTAMU CPEN ‘24 E: ***@***.***/in/amateoruizOn Nov 15, 2023, at 2:21 AM, Felix Hildén ***@***.***> wrote:﻿
Hi, just saw this referencing the issue I created, Tekore author here 👋 Thought I'd drop in to say if you just care about raw numbers and to build a feature (mind you I have very little context to what you're trying to do) we already have builtin paging iterators! Check this guide out.

**Comment by m-ruiz21** [comment]
fixed with commit 51d5084f99de27234c698030fea87804bdaa5e9f
